<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * Gets all posts from the post data source table.
     * It orders the result attending to each post creation date
     * in a descending sort.
     * 
     * @return array
     */
    public function getAllOrdered()
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->orderBy('p.date', 'DESC');
        
        return $qb->getQuery()->getResult();
    }

    /**
     * This method gets the total number of posts hosted at
     * the data source.
     * 
     * @return int
     */
    public function getTotalCount()
    {
        $qb = $this->createQueryBuilder('p')
            ->select('COUNT(p)');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
