# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.utilservice:
        class:  AppBundle\Service\UtilService
    app.forumservice:
        class:  AppBundle\Service\ForumService
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@app.paramfactory'
          - '@app.utilservice'
          - '%kernel.root_dir%/../web/%upload_dir%'
    app.postfactory:
        class:  AppBundle\Service\PostFactory
    app.paramfactory:
        class:  AppBundle\Service\ParamFactory
